-- Research Fellowship program (₹19,999 incl. GST) + refresh lab copy without em-dash taglines.

insert into public.courses (
  id, name, tagline, description, category, level, duration, format,
  schedule_summary, price_inr, currency, price_display, status,
  display_status, featured, features, seat_limit
) values
  (
    'frameworks-lab',
    'Frameworks Lab',
    'See with code. Ship vision projects.',
    'Build end-to-end computer vision skills from raw images and cleaning to classification, detection, and a GitHub portfolio employers can click and run.',
    'Course',
    'Beginner–Intermediate',
    '4 weeks',
    'Sat & Sun · 8 live classes',
    '8 live hours · 4 weekends · Campus Vision project',
    4999,
    'INR',
    '₹4,999',
    'published',
    'Open',
    true,
    '["Image pipelines with OpenCV","Hands-on PyTorch projects","Classification + detection demos","Portfolio-ready GitHub repos"]'::jsonb,
    null
  ),
  (
    'signal-lab',
    'Signal Lab',
    'From business question to deployed model.',
    'Go from a real business problem to clean data, trained models, and a live prediction API, then package the full workflow as a GitHub portfolio recruiters can run.',
    'Course',
    'Beginner–Intermediate',
    '4 weeks',
    'Sat & Sun · 8 live classes',
    '8 live hours · 4 weekends · Student Success Predictor project',
    4999,
    'INR',
    '₹4,999',
    'published',
    'Open',
    true,
    '["Business to ML problem framing","EDA, cleaning & feature craft","Model training & evaluation","FastAPI deploy + portfolio"]'::jsonb,
    null
  ),
  (
    'groundtruth-lab',
    'Groundtruth Lab',
    'Label data like a pro. ML-ready handoff.',
    'Design taxonomies, label real images, run quality checks, and ship documentation an ML engineer can import tomorrow. A GitHub portfolio that proves you belong in AI data ops.',
    'Course',
    'Beginner',
    '4 weeks',
    'Sat & Sun · 8 live classes',
    '8 live hours · 4 weekends · Campus Safety Labeling Kit project',
    4999,
    'INR',
    '₹4,999',
    'published',
    'Open',
    true,
    '["Taxonomy & guideline design","Hands-on Label Studio labeling","QA scripts & quality checks","ML handoff docs + portfolio"]'::jsonb,
    null
  ),
  (
    'research-fellowship',
    'Research Fellowship',
    '3-month AI research. Real projects. Real portfolio.',
    'Work in a 6-person research group on one serious AI problem in healthcare, agriculture, computer vision, or GenAI, and leave with a research-grade project, GitHub, technical report, and publication-oriented manuscript.',
    'Program',
    'Intermediate–Advanced',
    '3 months',
    'Live weekends · research groups of 6',
    '3 months · 30 seats · 5 research groups · publication-oriented output',
    19999,
    'INR',
    '₹19,999 · incl. GST',
    'published',
    'Applications Open',
    true,
    '["5 research groups · 30 seats only","Healthcare · Agri · CV · GenAI tracks","GitHub + research report + demo day","Publication-oriented manuscript guidance"]'::jsonb,
    30
  )
on conflict (id) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  category = excluded.category,
  level = excluded.level,
  duration = excluded.duration,
  format = excluded.format,
  schedule_summary = excluded.schedule_summary,
  price_inr = excluded.price_inr,
  currency = excluded.currency,
  price_display = excluded.price_display,
  status = excluded.status,
  display_status = excluded.display_status,
  featured = excluded.featured,
  features = excluded.features,
  seat_limit = excluded.seat_limit,
  updated_at = now();
